name: Test with Balena
description: Automate release testing with balenaCloud
branding:
  icon: code
  color: blue
inputs:
  balena_token:
    description: Your balenaCloud API token
    required: true
  fleet:
    description: Name of the fleet you want to build the release for
    required: true
  release_id:
    description: release ID of release to be tested
    required: true
  github_token:
    description: Github access token
    required: false
    default: ${{ github.token }}
  environment:
    description: Domain for the backend services to build your release
    required: false
    default: balena-cloud.com
  test_command:
    description: command to be run to start tests
    required: false
    default: exec npm install && exec npm run test
  test_timeout:
    description: timeout for tests
    required: false
    default: 100000
outputs:
  device_uuid:
    description: The UUID of the test device
runs:
  using: docker
  image: 'Dockerfile'
  env:
    BALENA_TOKEN: ${{ inputs.balena_token }}
    BALENA_URL: ${{ inputs.environment }}
    REGISTRY_SECRETS: ${{ inputs.registry_secrets }}